### ISSUE TITLE
lobby-fehler: movement aus jedem channel

### ISSUE THREAD

**Issue by grinder1337** [FrederikP/csgo-ts-mover#4]
moin, erstmal tolles tool!
ist zwar für die jungs etwas verwirrend, wenn sie dauernd beim retake in einen anderen channel geschoben werden, aber so soll es ja sein :)
mir ist aufgefallen, dass egal aus welchem channel die gemappten user verschoben werden.....
das ist irgendwie doof.
sprich das plugin schiebt jeden egal woher in einer der ct/t-channel, obwohl explizit die lobby angegeben wurde.
geht das irgendwie zu ändern, dass nur die aus der lobby verschoben werden?
gruss, Gr!nDeR

**Comment by FrederikP** [comment]
Hi,
ja das ist in der Tat im Moment nicht so eingebaut.
Ich hab gerade leider keine Zeit an dem Tool zu entwickeln. Vielleicht komme ich in nächster Zeit irgendwann dazu.
Wenn jemand von euch programmieren kann, dann kann derjenige auch gern einen Pull Request aufmachen und ich schau mir das dann an und merge es, wenns passt.

**Comment by FrederikP** [comment]
@JonasGoldt hat das netterweise gefixt. Aber wir haben es beide nicht getestet.
Wenn du das testen kannst @grinder1337 , sag Bescheid, ob es klappt oder nicht.

Musst nur die `ts-mover-service.py` auf den aktuellen Stand bringen.

Thx @JonasGoldt

**Comment by grinder1337** [comment]
moin, heute abend teste ich mal - danke für den schnellen support!
